Repository chris-greening/spyrograph, pull requests merged in 2023-04, with the labels that each got.

#88 Refactor cycloid constructor to _Cycloid
  setup.py
  spyrograph/_cycloid.py
  spyrograph/epitrochoid/epicycloid.py
  spyrograph/hypotrochoid/hypocycloid.py
Labels: enhancement

#90 Add scale feature
  setup.py
  spyrograph/_trochoid.py
  tests/_roulette.py
Labels: enhancement

#97 Add unit test for the zero or negative ValueError exception #95
  tests/_roulette.py
Labels: documentation, enhancement

#98 Added the latest blog post to the README blog section
  README.md
Labels: documentation

#100 Add descriptive __repr__
  setup.py
  spyrograph/_trochoid.py
  tests/_roulette.py
Labels: enhancement

#101 ADD: added n cusps docstring
  spyrograph/_cycloid.py
Labels: documentation

#103 Add examples to docstrings
  spyrograph/_trochoid.py
Labels: documentation

#107 Docstring improvement
  spyrograph/_trochoid.py
Labels: documentation

#108 Add animate function
  spyrograph/_trochoid.py
Labels: enhancement

#110 Fix cycloid animate method
  docs/_autosummary/spyrograph.epitrochoid.rst
  setup.py
  spyrograph/_cycloid.py
Labels: bug

#111 Add transform method
  setup.py
  spyrograph/_trochoid.py
  tests/_roulette.py
Labels: enhancement

#112 Fix scale origin value
  setup.py
  spyrograph/_trochoid.py
Labels: enhancement

#121 Improved docstring _init_turtles
  spyrograph/_trochoid.py
Labels: documentation

#120 Refactor create range
  setup.py
  spyrograph/_cycloid.py
  spyrograph/_misc.py
  spyrograph/_trochoid.py
  tests/_roulette.py
  tests/test_misc.py
Labels: enhancement

#124 Added parentheses to __repr__ thetas
  spyrograph/_trochoid.py
Labels: enhancement

#123 Added checking if the list of thetas is empty
  spyrograph/_trochoid.py
Labels: enhancement

#126 Run Pylint against _Cycloid
  spyrograph/_cycloid.py
Labels: enhancement

#127 Fix all existing Pylint flags
  spyrograph/_cycloid.py
  spyrograph/_misc.py
  spyrograph/_trochoid.py
  spyrograph/epitrochoid/epicycloid.py
  spyrograph/epitrochoid/epitrochoid.py
  spyrograph/hypotrochoid/hypocycloid.py
  spyrograph/hypotrochoid/hypotrochoid.py
Labels: enhancement

#129 Refactor functionality into _misc
  docs/source/spyrograph.core.rst
  spyrograph/core/_misc.py
  spyrograph/core/_trochoid.py
  tests/test_misc.py
Labels: enhancement

#130 Increase test coverage
  spyrograph/core/_trochoid.py
  tests/_trochoid.py
Labels: documentation

#132 Add screen coordinate feature
  spyrograph/core/_misc.py
  spyrograph/core/_trochoid.py
Labels: enhancement

#133 Add screensave option
  setup.py
  spyrograph/core/_misc.py
  spyrograph/core/_trochoid.py
Labels: enhancement

#134 Add animate screensize fix
  setup.py
  spyrograph/core/_misc.py
  spyrograph/core/_trochoid.py
Labels: enhancement

#136 Fix: Added the link in the blog post section
  README.md
Labels: documentation

#138 Add animate repeat feature
  setup.py
  spyrograph/core/_misc.py
  spyrograph/core/_trochoid.py
Labels: enhancement

#139 Add reverse feature
  setup.py
  spyrograph/core/_misc.py
  spyrograph/core/_trochoid.py
Labels: enhancement

#140 Add boomerang feature to animate
  setup.py
  spyrograph/core/_cycloid.py
  spyrograph/core/_misc.py
  spyrograph/core/_trochoid.py
Labels: enhancement

#141 Fix screen size draw
  setup.py
  spyrograph/core/_cycloid.py
  spyrograph/core/_trochoid.py
Labels: enhancement

#143 Added the docstring for _validate_theta function
  spyrograph/core/_misc.py
Labels: documentation

#148 fixing multiple return types
  spyrograph/core/_misc.py
  spyrograph/core/_trochoid.py
Labels: documentation

#154 Add translate method
  setup.py
  spyrograph/core/_trochoid.py
  tests/_trochoid.py
Labels: enhancement

#156 Fix issue #155
  README.md
Labels: documentation

#157 Add rotate method
  setup.py
  spyrograph/core/_cycloid.py
  spyrograph/core/_misc.py
  spyrograph/core/_trochoid.py
  tests/_cycloid.py
  tests/_trochoid.py
Labels: enhancement

#159 Updated docstring for _draw_circle method
  spyrograph/core/_trochoid.py
Labels: documentation

#160 Fix custom origin rotation
  setup.py
  spyrograph/core/_trochoid.py
Labels: bug

#163 Improve GitHub Action's
  .github/workflows/pylint.yaml
  .github/workflows/pytest.yaml
Labels: enhancement

#164 Refactor rotated shape
  spyrograph/core/_trochoid.py
Labels: enhancement
