Repository chris-greening/spyrograph, pull requests merged in 2023-03, with the labels that each got.

#2 Added GitHub repo configurations and files
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#3 Added better type hints to all functions
  spyrograph/_roulette.py
  spyrograph/epicycloid.py
  spyrograph/epitrochoid.py
  spyrograph/hypocycloid.py
  spyrograph/hypotrochoid.py
Labels: documentation

#4 Add module level docstrings describing the different objects
  spyrograph/_roulette.py
  spyrograph/epicycloid.py
  spyrograph/epitrochoid.py
  spyrograph/hypocycloid.py
  spyrograph/hypotrochoid.py
Labels: documentation

#7 Add deltoid.Deltoid object
  README.md
  spyrograph/__init__.py
  spyrograph/deltoid.py
Labels: enhancement

#8 Add astroid.Astroid object
  spyrograph/__init__.py
  spyrograph/astroid.py
Labels: enhancement

#9 Added ability to specify background color of the screen
  spyrograph/_roulette.py
Labels: enhancement

#11 Add optional matplotlib functionality
  spyrograph/_roulette.py
Labels: enhancement

#12 Add pandas functionality to _Roulette
  spyrograph/_roulette.py
Labels: enhancement

#17 Add theta step functionality
  spyrograph/_roulette.py
Labels: enhancement

#19 Modify theta end argument to theta stop
  spyrograph/_roulette.py
  spyrograph/astroid.py
  spyrograph/deltoid.py
  spyrograph/epicycloid.py
  spyrograph/hypocycloid.py
Labels: enhancement

#18 Add ellipse as a special case of hypotrochoid
  spyrograph/__init__.py
  spyrograph/ellipse.py
Labels: enhancement

#25 Add cardioid object
  docs/_autosummary/spyrograph.ellipse.rst
  docs/_autosummary/spyrograph.tusi_couple.rst
  docs/index.rst
  docs/source/spyrograph.cardioid.rst
  setup.py
  spyrograph/__init__.py
  spyrograph/cardioid.py
Labels: enhancement

#26 Add nephroid object
  docs/index.rst
  docs/source/spyrograph.nephroid.rst
  setup.py
  spyrograph/nephroid.py
Labels: enhancement

#27 Add ranuncloid object
  docs/index.rst
  docs/source/spyrograph.ranuncloid.rst
  setup.py
  spyrograph/ranuncloid.py
Labels: enhancement

#28 Add full path trace
  spyrograph/_roulette.py
Labels: enhancement

#46 requirements.txt #36
  requirements.txt
Labels: documentation

#47 Modify requirements.txt with relevant libraries
  requirements.txt
Labels: documentation

#48 Add Pylint GitHub Action for simple linting on push
  .github/workflows/pylint.yaml
  setup.py
Labels: enhancement

#49 Refactor objects into their own subpackages
  .github/workflows/pylint.yaml
  docs/conf.py
  docs/index.rst
  docs/source/spyrograph.epitrochoid.cardioid.rst
  docs/source/spyrograph.epitrochoid.epicycloid.rst
  docs/source/spyrograph.epitrochoid.epitrochoid.rst
  docs/source/spyrograph.epitrochoid.nephroid.rst
  docs/source/spyrograph.epitrochoid.ranuncloid.rst
  docs/source/spyrograph.hypotrochoid.astroid.rst
  docs/source/spyrograph.hypotrochoid.deltoid.rst
  docs/source/spyrograph.hypotrochoid.ellipse.rst
  docs/source/spyrograph.hypotrochoid.hypocycloid.rst
  docs/source/spyrograph.hypotrochoid.hypotrochoid.rst
  docs/source/spyrograph.hypotrochoid.tusi_couple.rst
  setup.py
  spyrograph/__init__.py
  spyrograph/epitrochoid/__init__.py
  spyrograph/epitrochoid/cardioid.py
  spyrograph/epitrochoid/epicycloid.py
  spyrograph/epitrochoid/epitrochoid.py
  spyrograph/epitrochoid/nephroid.py
  spyrograph/epitrochoid/ranuncloid.py
  spyrograph/hypotrochoid/__init__.py
  spyrograph/hypotrochoid/astroid.py
  spyrograph/hypotrochoid/deltoid.py
  spyrograph/hypotrochoid/ellipse.py
  spyrograph/hypotrochoid/hypocycloid.py
  spyrograph/hypotrochoid/hypotrochoid.py
  spyrograph/hypotrochoid/tusi_couple.py
Labels: enhancement

#51 Fix validate theta method
  setup.py
  spyrograph/_roulette.py
Labels: bug

#52 Add numpy dependency
  .github/workflows/pylint.yaml
  README.md
  setup.py
  spyrograph/_roulette.py
Labels: enhancement

#53 Add cusp routine factory method
  .pylintrc
  setup.py
  spyrograph/_cycloid.py
  spyrograph/_trochoid.py
  spyrograph/epitrochoid/__init__.py
  spyrograph/epitrochoid/epicycloid.py
  spyrograph/epitrochoid/epitrochoid.py
  spyrograph/epitrochoid/special/__init__.py
  spyrograph/epitrochoid/special/cardioid.py
  spyrograph/epitrochoid/special/nephroid.py
  spyrograph/epitrochoid/special/ranuncloid.py
  spyrograph/hypotrochoid/__init__.py
  spyrograph/hypotrochoid/hypocycloid.py
  spyrograph/hypotrochoid/hypotrochoid.py
  spyrograph/hypotrochoid/special/__init__.py
  spyrograph/hypotrochoid/special/astroid.py
  spyrograph/hypotrochoid/special/deltoid.py
  spyrograph/hypotrochoid/special/ellipse.py
  spyrograph/hypotrochoid/special/tusi_couple.py
  tests/_roulette.py
Labels: enhancement

#55 Add repeat argument to trace instancemethod
  docs/source/spyrograph.epitrochoid.special.cardioid.rst
  docs/source/spyrograph.epitrochoid.special.nephroid.rst
  docs/source/spyrograph.epitrochoid.special.ranuncloid.rst
  docs/source/spyrograph.epitrochoid.special.rst
  docs/source/spyrograph.hypotrochoid.special.astroid.rst
  docs/source/spyrograph.hypotrochoid.special.deltoid.rst
  docs/source/spyrograph.hypotrochoid.special.ellipse.rst
  docs/source/spyrograph.hypotrochoid.special.rst
  docs/source/spyrograph.hypotrochoid.special.tusi_couple.rst
  setup.py
  spyrograph/_trochoid.py
Labels: enhancement

#57 Remove old rst files and add :inherited-members:
  docs/source/spyrograph.astroid.rst
  docs/source/spyrograph.cardioid.rst
  docs/source/spyrograph.deltoid.rst
  docs/source/spyrograph.ellipse.rst
  docs/source/spyrograph.epicycloid.rst
  docs/source/spyrograph.epitrochoid.cardioid.rst
  docs/source/spyrograph.epitrochoid.nephroid.rst
  docs/source/spyrograph.epitrochoid.ranuncloid.rst
  docs/source/spyrograph.epitrochoid.special.cardioid.rst
  docs/source/spyrograph.epitrochoid.special.nephroid.rst
  docs/source/spyrograph.epitrochoid.special.ranuncloid.rst
  docs/source/spyrograph.hypotrochoid.astroid.rst
  docs/source/spyrograph.hypotrochoid.deltoid.rst
  docs/source/spyrograph.hypotrochoid.ellipse.rst
  docs/source/spyrograph.hypotrochoid.special.astroid.rst
  docs/source/spyrograph.hypotrochoid.special.deltoid.rst
  docs/source/spyrograph.hypotrochoid.special.ellipse.rst
  docs/source/spyrograph.hypotrochoid.special.tusi_couple.rst
Labels: documentation

#58 Add custom origin
  setup.py
  spyrograph/_cycloid.py
  spyrograph/_trochoid.py
  spyrograph/epitrochoid/epicycloid.py
  spyrograph/hypotrochoid/hypocycloid.py
  tests/_roulette.py
Labels: enhancement

#59 Add docs for constructors
  setup.py
  spyrograph/_trochoid.py
  spyrograph/epitrochoid/epicycloid.py
  spyrograph/hypotrochoid/hypocycloid.py
Labels: documentation

#61 Add object creation classmethod
  spyrograph/_cycloid.py
  spyrograph/_trochoid.py
  spyrograph/epitrochoid/epicycloid.py
  spyrograph/hypotrochoid/hypocycloid.py
Labels: enhancement

#62 Increase test coverage
  spyrograph/_trochoid.py
  tests/_roulette.py
Labels: enhancement

#60 Add animation classmethod
  spyrograph/_trochoid.py
Labels: enhancement, help wanted, good first issue

#64 Modify update behavior to instantly draw
  spyrograph/_trochoid.py
Labels: enhancement

#67 Add width feature
  setup.py
  spyrograph/_trochoid.py
Labels: enhancement

#69 Update README.md With Blog Posts
  README.md
Labels: documentation

#78 Increase unit test coverage
  tests/_roulette.py
Labels: enhancement

#79 Refactor turtle instantiations into a namedtuple
  setup.py
  spyrograph/_trochoid.py
Labels: enhancement

#87 Improved the `Epitrochoic` class docstring
  spyrograph/epitrochoid/epitrochoid.py
Labels: documentation

#86 Improved the `Epicycloid` class docstring
  spyrograph/epitrochoid/epicycloid.py
Labels: documentation

#85 Improved the `Hypocycloid` class docstring
  spyrograph/hypotrochoid/hypocycloid.py
Labels: documentation
